### ISSUE TITLE
UBC stairs ID system

### ISSUE THREAD

**Issue by TheOddlySeagull** [LemADEC/UndergroundBiomesConstructs-Aang23#8] opened 2022-09-12 05:13 UTC
Hello there, I have an issue, not sure if it'll get fixed or not, but I would love to.
It seems that UB stairs do not rely on NBT for rotation, but each rotation has its own ID, causing compatibility issues with other mods that relies on stair rotation to flip/rotate/move structures (Ancient Warfare structures in my case).
Would be great if stairs would be modified to support a "facing:" data rather than block ID, like vanilla and most mods (Rustic, Biomes O Plenty…)

I am still running on Minecraft 1.12.2

**Comment by TheOddlySeagull** [comment] 2022-09-12 15:39
In some other words, rather than having stuff like "undergroundbiomes:igneous_brick_stairs_south", have "undergroundbiomes:igneous_brick_stairs" with "facing:"south"" tag

**Comment by LemADEC** [comment] 2022-09-12 19:30
Duplicate of https://github.com/Aang23/UndergroundBiomesConstructs/issues/19
Long story short, there's no way to fix that on 1.12.2.
Also, for the record, stairs do NOT have NBT data, they are not tile entities. Vanilla stairs are coding facing information in block properties (previously known as metadata). UBC stairs are encoding stone variations in block properties, stone class and facing information in block ids.

**Comment by slava110** [comment] 2022-10-01 08:03
> Duplicate of [Aang23#19](https://github.com/Aang23/UndergroundBiomesConstructs/issues/19) Long story short, there's no way to fix that on 1.12.2. Also, for the record, stairs do NOT have NBT data, they are not tile entities. Vanilla stairs are coding facing information in block properties (previously known as metadata). UBC stairs are encoding stone variations in block properties, stone class and facing information in block ids.

I'm interested in why it isn't possible. Metadata limit? Or something else?

**Comment by LemADEC** [comment] 2022-10-04 18:49
there's no proper way to convert a block without duplicating all related ids and codes. In other words, without making a huge constrains on the mod and existing worlds.  
Furthermore, if it was "easy", mods that already support rotation with the current scheme will break while we're on an obsolete version of the base game.

**Comment by slava110** [comment] 2022-10-04 18:59
> there's no proper way to convert a block without duplicating all related ids and codes. In other words, without making a huge constrains on the mod and existing worlds.

Okay, what do you mean by `convert a block`?
> Furthermore, if it was "easy", mods that already support rotation with the current scheme will break while we're on an obsolete version of the base game.

Which mods do support this rotation type of UBC currently? WarpDrive? The only dependent mod I see on the CurseForge is `Pyrotech Compat` mod which... Doesn't care about stairs I think. Just about drops.

**Comment by LemADEC** [comment] 2022-10-04 19:27
No, I'm not making an overcomplicated change for it, neither the previous maintainers.  
Now, please do stop arguing about it, just accept it or make a pull request to do it.

**Closed as completed by LemADEC** 2022-10-04 19:27 UTC
